Vagrant.configure("2") do |config|
	config.vm.box = "leandrocalmeida/ubuntu"
	config.vm.box_version = "02"
	config.vm.network "private_network", ip: "172.16.0.200", netmask: "16"
	config.vm.network "forwarded_port", guest: 8080, host:8083	
	config.vm.provision "docker" do |d|
           d.build_image "/vagrant",
	     args: "-t webserverapache"
	   d.run "webserverapache",
	      image: "webserverapache:latest",
              args: "-p 8080:80 " + "-v /vagrant/public-html:/usr/local/apache2/htdocs/"
        end
end
