Vagrant.configure("2") do |config|
	config.vm.box = "leandrocalmeida/ubuntu"
	config.vm.box_version = "02"
	config.vm.network "private_network", ip: "172.16.0.200", netmask: "16"
	config.vm.network "forwarded_port", guest: 8080, host:8082
	config.vm.provision "docker" do |d|
           d.run "hello-world"
        end
end
