Vagrant.configure("2") do |config|
	config.vm.box = "leandrocalmeida/ubuntu"
	config.vm.box_version = "02"
	config.vm.network "private_network", ip: "172.16.0.200", netmask: "16"
	config.vm.network "forwarded_port", guest:80, host: 8080
end
